

ALTER TABLE users
ADD COLUMN surname TEXT DEFAULT 'none',
ADD COLUMN avatar_url TEXT DEFAULT 'none',
ADD COLUMN bio TEXT DEFAULT '',
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;